### ISSUE TITLE
xajax-examples no longer work

### ISSUE THREAD

**Issue by edrobinson** [lagdo/xajax-core#1]
The hello world examples in xajax-examples no longer work as the constructor is now private and needs changed to $xajax = Xajax::getInstance(); Happened after doing a composer update.

**Comment by zigmoo** [comment]
Hello Ed and Thierry, is the private constructor to force the use of the singleton pattern as discussed here (https://codeigniter.com/user_guide/general/creating_libraries.html#utilizing-codeigniter-resources-within-your-library)?

**Comment by feuzeu** [comment]
Since commit #384ed2d, the main Xajax class is a singleton. There's only one instance of the class, which you can access anywhere in your code with the Xajax::getInstance() call.
The examples were updated accordingly.
