### ISSUE TITLE
Seeking CodeIgniter Library Advice?

### ISSUE THREAD

**Issue by zigmoo** [lagdo/xajax-core#2]
Hello Thierry & Ed,

Can you offer any advice on creating a CodeIgniter 3 Library for Xajax-core?

The start I've made so far:

	<?php if ( ! defined("BASEPATH")) exit("No direct script access allowed");
	require (APPPATH . "../vendor/autoload.php");
	use Xajax\Xajax;
	use Xajax\Response\Response;
	
	class CI_Xajax {

	public $xajax;

	public function __construct()
	{
		$this->xajax = Xajax::getInstance();
			$this->_ci   =& get_instance();
		}
	}

Currently, I've placed the line

> $this->load->library(array('CI_Xajax', 'session'));

in the welcome->__construct() method, and the library loads with no errors. 
However, not sure yet if this is working, since I can't figure out how to actually access the resulting $ci->ci_xajax object in my controller.

**Comment by zigmoo** [comment]
Should I be trying to integrate Keradus/Psr4Autoloader into the CodeIgniter Xajax Library to get it to perform the loading instead of literal `use` statements?

**Comment by zigmoo** [comment]
Maybe a better place to discuss it is at [xajax-projects](http://community.xajax-project.org/post/34102/#p34102) in a CodeIgniter forum [thread](http://forum.codeigniter.com/thread-65065-post-331603.html#pid331603)...

**Comment by feuzeu** [comment]
I've answered in the Xajax forum http://community.xajax-project.org/topic/9390/the-new-xajax-is-out-and-the-new-xajax-is-cool/
