### ISSUE TITLE
Xajax debug interface missing?

### ISSUE THREAD

**Issue by zigmoo** [lagdo/xajax-core#3]
When I attempt to use the xajax debug window:
'$this->xajax->setOption('core.debug.on', 1);'

I get the javascript alert:
The xajax.debug javascript component could not be included. Perhaps the URL is incorrect?
URL: //assets.lagdo-software.net/libs/xajax/js/latest/xajax.debug.js

**Comment by feuzeu** [comment]
Fixed in commit #c07cf6611dcaa64ec938accda6608c1794bdaf49.
The javascript file //assets.lagdo-software.net/libs/xajax/js/latest/xajax.debug.js was not loaded even when the debug option is set to true.

**Comment by feuzeu** [comment]
Fixed in commit c07cf6611dcaa64ec938accda6608c1794bdaf49.
The javascript file //assets.lagdo-software.net/libs/xajax/js/latest/xajax.debug.js was not loaded even if the debug option was set to true.
